language: cpp
dist: focal

os:
  - linux
  - osx
#  - windows

compiler:
  - gcc
  - clang

install:
  - |-
      case $TRAVIS_OS_NAME in
        "linux")
          sudo apt-get update
          sudo apt-get install -y libgpm-dev libncurses5-dev
          ;;
      esac

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - |-
      case $TRAVIS_OS_NAME in
        "windows")
          cmake --build . --target ALL_BUILD --config Release
          ;;
        "linux"|"osx")
          make
          ;;
      esac

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode9.4  
    - os: windows
      dist: server-2016
