language: cpp
dist: bionic

os:
  - linux
  - windows

compiler:
  - gcc
  - clang

install:
  - |-
      case $TRAVIS_OS_NAME in
        "linux")
          sudo apt-get install -y libgpm-dev libncurses5-dev
          ;;
      esac

script:
  - cd TextConsole
  - cmake -B _build -S .
  - cd _build
  - |-
      case $TRAVIS_OS_NAME in
        "windows")
          cmake --build . --target ALL_BUILD --config Release
          ;;
        "linux")
          make
          ;;
      esac

jobs:
  include:
    - os: linux
      dist: trusty
    - os: windows
      dist: server-2016
