language: cpp
dist: bionic

os:
  - linux
  - windows

compiler:
  - gcc
  - clang

install:
  - |-
      case $TRAVIS_OS_NAME in
        "linux")
          sudo apt-get update
          sudo apt-get install -y libgpm-dev libncurses5-dev
          sudo apt-get install -y g++-8 gcc-8
          export CXX="g++-8" CC="gcc-8"
          ;;
      esac

script:
  - cd TextConsole
  - mkdir _build
  - cd _build
  - cmake ..
  - |-
      case $TRAVIS_OS_NAME in
        "windows")
          cmake --build . --target ALL_BUILD --config Release
          ;;
        "linux")
          make
          ;;
      esac

jobs:
  include:
    - os: linux
      dist: bionic
    - os: windows
      dist: server-2016
