language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode12
      
    - os: freebsd
    
#    - os: linux
#      dist: focal
#      compiler: clang

#    - os: windows
#      dist: server-2016

install:
  - |-
      case $TRAVIS_OS_NAME in
        "linux")
          sudo apt-get update
          sudo apt-get install -y libgpm-dev libncurses5-dev
          ;;
      esac

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - |-
      case $TRAVIS_OS_NAME in
        "windows")
          cmake --build . --target ALL_BUILD --config Release
          ;;
        "linux"|"osx"|"freebsd")
          make
          ;;
      esac
