version: 2.0.0-MVP-beta-{build}

branches:
  only:
    - main

image:
    - Visual Studio 2019

configuration:
    - Release

before_build:
    - cmd: cmake -H. -B./build

build:
    project: Multitextor.sln
    verbosity: normal
