version: 2.0.0.{build}-MVP-beta

branches:
  only:
    - main

image:
    - Visual Studio 2019

configuration:
    - Release

before_build:
    - cmd: cmake -H. -B./build

build:
    project: build/Multitextor.sln
    verbosity: normal

artifacts:
    - path: '_build/bin/$(configuration)/multitextor.exe'
      name: Multitextor
